=== BioinfoPZH/plepiseq_json/output_subschemes/viral_genome.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Subschema for plepiseq output, statistic information regarding viral genome.",
  "comment": "Schemat dla outputu, statystyczne informacja o genomie wirusowym proponowanym dla probki.",
  "type": "object",
  "properties": {
    "error_message": {
      "type": "string",
      "minLength": 1,
      "comment": "Dowolny tekst zwracany jako komunikat bledu podczas przewidywania genomu wirusowego. Wymagany, jesli status to blad."
    },
    "status": {
      "type": "string",
      "enum": [
        "tak",
        "nie",
        "blad"
      ],
      "comment": "Informacja czy zaproponowano genom wirusa dla probki, nieprzewidziano, zwrocono blad. Wymagany."
    },
    "total_length_value": {
      "type": "number",
      "minimum": 0,
      "multipleOf": 1,
      "comment": "Calkowita dlugosc genomu. Wymagany."
    },
    "average_coverage_value": {
      "type": "number",
      "multipleOf": 0.01,
      "comment": "Srednie pokrycie dla zaproponowanego genomu, z dokladnoscia do maksymalnie 2 miejsc po przecinku. Wymagany."
    },
    "number_of_Ns_value": {
      "type": "number",
      "multipleOf": 1,
      "minimum": 0,
      "comment": "Ilosc nieokreslonych nukleotydow zidentyfikowana w genomie."
    },
    "number_of_ambiguous_value": {
      "type": "number",
      "multipleOf": 1,
      "minimum": 0,
      "comment": "Ilosc niejednoznacznych nukleotydow (kody IUPAC R, Y, S, W, K, M, B, D, H, V) zidentyfikowanych w genomie. Nukleotydy oznaczone jako N nie sa wliczane do tej wartosci."
    },
    "coverage_histogram_file": {
      "type": "string",
      "minLength": 1,
      "comment": "Sciezka do pliku pozwalajacego narysowac histogram pokrycia w calym genomie."
    },
    "coverage_barplot_data": {
      "type": "array",
      "minItems": 1,
      "comment": "Dane informujace o pokryciu na kazdej pozycji. Kazdy segment ma oddzielny plik.",
      "items": {
        "type": "object",
        "properties": {
          "segment_name": {
            "type": "string",
            "minLength": 1,
            "comment": "Nazwa segmentu dla ktorego prezentujemy dane. Wymagany."
          },
          "segment_file": {
            "type": "string",
            "minLength": 1,
            "comment": "Sciezka do pliku zawierajacego dane do barplotu z pokryciem. Wymagany."
          }
        },
        "required": [
          "segment_name",
          "segment_file"
        ],
        "additionalProperties": false
      }
    },
    "primer_usage_data": {
      "type": "array",
      "minItems": 1,
      "comment": "Lista uzycia primerow oddzielnie dla kazdego z segmentow.",
      "items": {
        "type": "object",
        "properties": {
          "segment_name": {
            "type": "string",
            "minLength": 1,
            "comment": "Nazwa segmentu dla ktorego podajemy uzycie primerow."
          },
          "primer_data": {
            "type": "array",
	    "minItems": 1,
            "items": {
              "type": "object",
              "properties": {
                "primer_name": {
                  "type": "string",
                  "minLength": 1,
                  "comment": "Nazwa primeru."
                },
                "primer_usage": {
                  "type": "number",
                  "multipleOf": 1,
                  "comment": "Ilosc odczytow mapujacych sie 5' lub 3' koncem na primer."
                }
              },
              "required": [
                "primer_name",
                "primer_usage"
              ],
              "additionalProperties": false
            }
          }
        },
        "required": [
          "segment_name",
          "primer_data"
        ],
        "additionalProperties": false
      }
    }
  },
  "required": [
    "status"
  ],
  "additionalProperties": false,
  "allOf": [
    {
      "if": {
        "properties": {
          "status": {
            "const": "tak"
          }
        }
      },
      "then": {
        "required": [
          "total_length_value",
          "average_coverage_value",
          "number_of_Ns_value",
          "number_of_ambiguous_value",
          "coverage_histogram_file",
          "coverage_barplot_data",
          "primer_usage_data"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "status": {
            "enum": [
              "nie",
              "blad"
            ]
          }
        }
      },
      "then": {
        "required": [
          "error_message"
        ]
      }
    }
  ]
}

=== BioinfoPZH/plepiseq_json/output_subschemes_examples/viral_genome_example_1.json
{
  "status": "tak",
  "total_length_value": 1234,
  "average_coverage_value": 100.34,
  "number_of_Ns_value": 34,
  "number_of_ambiguous_value": 5,
  "coverage_histogram_file": "/path/to/a/file",

  "coverage_barplot_data": [
    {
      "segment_name": "MN09345",
      "segment_file": "/path/to/a/file"
    }
  ],
  "primer_usage_data": [
    {
      "segment_name": "chr4_HA",
      "primer_data": [
        {
          "primer_name": "Primer1",
          "primer_usage": 10
        },
        {
          "primer_name": "Primer1",
          "primer_usage": 10
        }
      ]
    }
  ]
}
